x = 0:0.033:30;
x_seg = 12.375000000000000:.033:22.803000000000001;
N_f = length(x);

signal = zeros(length(x),1);
signal(376:692) = 150*abs(square(x_seg));

%%

gamma = .3;
w_0 = 7.5;

y0 = [0; 0]; %IC for y and y'
    
para = @(t) interp1(x, signal, t, 'pchip', 0);
    
dydt = @(t,y)[y(2); -(2*gamma)*y(2) - (w_0)^2*y(1) + para(t)]; %Actual ODE is here.
    

[t,y] = ode45(dydt, x, y0); %ODE45 solver call, generating phi data
    
phi_gen = y(:,1)'; %generated phi data

plot_settings(1)

f1 = figure(1);
theme(f1,"light");
hold on
plot(x, phi_gen, 'Color',[227/255,159/255,246/255])
legend('Generated $$\phi(t)$$')
title("$\phi(t)$ Generated by Square Torque Signal")
xlabel("t")
ylabel("$$\phi(t)$$")
ylim([-3,6])
yticks((-3:1:6))
hold off


%Plots output
f = figure(2);
theme(f,"light");
hold on
plot(x, signal, 'Color',[227/255,159/255,246/255])
legend('Torque Signal')
title("Rachel Made Square Wave")
xlabel("t")
ylabel("$$\tau(t)$$")
ylim([-10,180])
hold off




